### ISSUE TITLE
你好！我已经下载好了测试集的数据了，请问有train数据集吗？googleDrive的下载不了，

### ISSUE THREAD

**Issue by zj56** [PeterWang512/CNNDetection#25]
你好！我已经下载好了测试集的数据了，请问有train数据集吗？googleDrive的下载不了，
oneDrive的test数据集已经可以下载，所以最好有oneDrive的train数据集。

_Originally posted by @zj56 in https://github.com/PeterWang512/CNNDetection/issues/10#issuecomment-1817431998_

**Comment by DongChengdongHangZhou** [comment]
训练集的google drive链接给我 我帮你下载

**Comment by zj56** [comment]
https://drive.google.com/drive/folders/14E_R19lqIE9JgotGz09fLPQ4NVqlYbVc

**Comment by DongChengdongHangZhou** [comment]
This is the onedrive link to download the training dataset:

https://connectpolyu-my.sharepoint.com/:f:/g/personal/21041667r_connect_polyu_hk/EuFwHXNFWzpNuJPQ-j9ymzYB8BXarD8C0SP81HE0rrR3zA?e=pbV7MD

**Comment by zj56** [comment]
Thank you very much!!!!

**Comment by PeterWang512** [comment]
I am planning to update the download options with huggingface dataset links. Will that help with your case?

**Comment by DORAEMON-MAN** [comment]
> I am planning to update the download options with huggingface dataset links. Will that help with your case?

That will be so helpful. Thank you very much!

**Comment by PeterWang512** [comment]
The download link has been changed to HuggingFace now! Feel free to pull the new repo and try it :)
