### ISSUE TITLE
Hi, We can't download "testset.zip”

### ISSUE THREAD

**Issue by Tsingtong** [PeterWang512/CNNDetection#4]
Cause Google Drive rules, we can't download "testset.zip”, please check it, Thank you.

**Comment by PeterWang512** [comment]
I checked and both the link and the script are still working for me.
Do you mind check if this link works? https://drive.google.com/uc?export=download&id=1z_fD3UKgWQyOTZIBbYSaQ-hz4AzUrLC1
If it works, maybe you can try download it manually? Thanks!

**Comment by Tsingtong** [comment]
> I checked and both the link and the script are still working for me.
> Do you mind check if this link works? https://drive.google.com/uc?export=download&id=1z_fD3UKgWQyOTZIBbYSaQ-hz4AzUrLC1
> If it works, maybe you can try download it manually? Thanks!

Yeah, It does, Thanks.
