### ISSUE TITLE
About training and validation

### ISSUE THREAD

**Issue by wheatdog** [PeterWang512/CNNDetection#7]
Thanks for releasing the training code.
I got the following error while in the validation stage of the training code.

```
saving the latest model blur_jpg_prob0.1 (epoch 0, model.total_steps 10000)
Train loss: 0.06095101684331894 at step: 10400
Train loss: 0.05730269104242325 at step: 10800
Train loss: 0.02164740115404129 at step: 11200
saving the model at the end of epoch 0, iters 11252
Traceback (most recent call last):
  File "train.py", line 79, in <module>
    acc, ap = validate(model.model, val_opt)[:2]
  File "/home/lyt/prj/06-18-CNNDetection/validate.py", line 11, in validate
    data_loader = create_dataloader(opt)
  File "/home/lyt/prj/06-18-CNNDetection/data/__init__.py", line 32, in create_dataloader
    dataset = get_dataset(opt)
  File "/home/lyt/prj/06-18-CNNDetection/data/__init__.py", line 12, in get_dataset
    dset = dataset_folder(opt, root)
  File "/home/lyt/prj/06-18-CNNDetection/data/datasets.py", line 20, in dataset_folder
    return binary_dataset(opt, root)
  File "/home/lyt/prj/06-18-CNNDetection/data/datasets.py", line 59, in binary_dataset
    elif opt.no_crop:
AttributeError: 'Namespace' object has no attribute 'no_crop'
```

I believe this is caused by the recent update of testing with uncropped image. My current fix is to add
```
val_opt.no_crop = False
```
in `get_val_opt`
https://github.com/PeterWang512/CNNDetection/blob/10df9f54a1e7983bc7f8078b88e7a8591717c021/train.py#L18-L31

I guess this should do it. However, I have some questions,

- It seems that `train.py` uses the whole training set as the validation set. Is it the expected behavior? To my understand, the training set and the validation should be disjoint most of the time.
- How did you pick the final model? Did you just pick the one that did the best on validation set (that is, the model has the highest accuracy on the validation (training) set) as the final model and test them on other datasets?

Thanks!

**Comment by PeterWang512** [comment]
Yes, both the no_crop option and validation are bugs introduced when I'm rearranging the code during release. Thanks so much for the catch, and I'll fix the code soon!

We use model_epoch_best.pth for the final model, and it is the best model on validation set.

**Comment by PeterWang512** [comment]
The code is updated and the bugs should be resolved. Thanks!
