### ISSUE TITLE
issue in validate.py  while training?

### ISSUE THREAD

**Issue by mwunder424** [PeterWang512/CNNDetection#8]
First of all, nice work, and thank you for releasing the training side, I had also seen and fixed the opt.no_crop, but I have encountered another run stopper while training.  
I have included a few print outs.
Can you assist please?

validate.py y_true:  [0 0 0 ... 5 5 5]
validate.py y_pred:  [3.80192695e-08 1.54170243e-09 2.35934561e-09 ... 1.00000000e+00
 1.00000000e+00 1.00000000e+00]
validate.py acc_score:  0.3323639385126714
Traceback (most recent call last):
  File "train.py", line 79, in <module>
    acc, ap = validate(model.model, val_opt)[:2]
  File "/cnndetection/validate.py", line 26, in validate
    ap = average_precision_score(y_true, y_pred)
  File "/cnndetection/venvCnn/lib/python3.6/site-packages/sklearn/metrics/_base.py", line 74, in _average_binary_score
    raise ValueError("{0} format is not supported".format(y_type))
ValueError: multiclass format is not supported

**Comment by mwunder424** [comment]
eval.py has no issues with the same dataset, this issue only occurs on train.py

**Comment by PeterWang512** [comment]
I haven't seen this error before. But before digging into this, would you mind trying out the updated code and see if this error shows up again? Thanks!

**Comment by mwunder424** [comment]
The updated code seems to have done the trick, thanks
